services:
  - type: web
    name: control-mantenimiento
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
