services:
  - type: web
    name: control-mantenimiento
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/control_mantenimiento
